replicaCount: 5

image:

  tag: v2.0.0


resources:

  requests:

    cpu: 500m

    memory: 512Mi


ingress:

  hosts:

  - host: day56.example.com
    paths:
        - path: /
          pathType: Prefix
