replicaCount: 1

image:
  repository: day56-demo
  tag: dev
  pullPolicy: IfNotPresent

resources:

  requests:
    cpu: 50m
    memory: 64Mi


ingress:

  hosts:

  - host: dev.day56.local
    paths:
        - path: /
          pathType: Prefix
