apiVersion: v1
kind: Pod

metadata:
  name: nginx-config-volume

spec:
  containers:
    - name: nginx
      image: docker.m.daocloud.io/library/nginx:latest

      volumeMounts:
        - name: config-volume
          mountPath: /etc/config

  volumes:
    - name: config-volume
      configMap:
        name: app-config-file
