apiVersion: v1
kind: Pod

metadata:
  name: nginx-config

spec:
  containers:
    - name: nginx
      image: docker.m.daocloud.io/library/nginx:latest

      env:
        - name: APP_NAME
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: APP_NAME

        - name: VERSION
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: VERSION
