apiVersion: v1
kind: Pod

metadata:
  name: secret-volume-demo

spec:

  containers:
  - name: nginx
    image: docker.m.daocloud.io/library/nginx:latest

    volumeMounts:
    - name: secret-volume
      mountPath: /etc/secret


  volumes:
  - name: secret-volume
    secret:
      secretName: db-secret
