name: Day50 Docker Build


on:

  workflow_dispatch:


jobs:

  build:

    runs-on: self-hosted


    steps:

    - name: Checkout

      uses: actions/checkout@v4


    - name: Docker Build

      run: |

        docker build \
        -t day50-demo:v1 \
        ./app


    - name: Runner Info
      run: |
        hostname
        docker info | grep "Server Version"
