name: Day18 Secrets Demo

on:
  workflow_dispatch:

env:
  PROJECT: "Project Shanghai"

jobs:
  demo:
    runs-on: ubuntu-latest

    steps:
      - name: Show Environment Variable
        run: echo "Project: $PROJECT"
        
      - name: Show Secret
        env:
          MY_NAME: ${{ secrets.MY_NAME }}
        run: echo "Hello $MY_NAME"
